apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-config
  namespace: argocd
  labels:
    app.kubernetes.io/name: cert-manager-config
    app.kubernetes.io/part-of: security
  annotations:
    description: "管理 cert-manager 的配置资源，包括 ClusterIssuer 和证书"
spec:
  project: infrastructure
  sources:
    - repoURL: https://github.com/lixiaojun2914/demo-infra
      targetRevision: main
      path: gitops/infrastructure/security/cert-manager
  destination:
    server: https://kubernetes.default.svc
    # ClusterIssuer 是集群级别资源，不需要指定命名空间
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - SkipDryRunOnMissingResource=true
      - ServerSideApply=true
