apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
  labels:
    app.kubernetes.io/name: istio
    app.kubernetes.io/part-of: infrastructure
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: infrastructure
  sources:
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: istiod
      targetRevision: 1.25.4
      helm:
        releaseName: istiod
        valueFiles:
          - $values/gitops/infrastructure/istio/values/istiod.yaml
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: gateway
      targetRevision: 1.25.4
      helm:
        releaseName: istio-ingress
        valueFiles:
          - $values/gitops/infrastructure/istio/values/gateway.yaml
    - repoURL: https://github.com/lixiaojun2914/demo-infra
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - SkipDryRunOnMissingResource=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
