apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-gateway-config
  namespace: argocd
  labels:
    app.kubernetes.io/name: istio-gateway-config
    app.kubernetes.io/part-of: infrastructure
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/lixiaojun2914/demo-infra
    targetRevision: main
    path: gitops/infrastructure/istio
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - SkipDryRunOnMissingResource=true
      - ServerSideApply=true
