# 开发环境资源配额
apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-quota
  namespace: dev
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: 1Gi
    limits.cpu: "1000m"
    limits.memory: 2Gi
    pods: "10"
---
# 预发布环境资源配额
apiVersion: v1
kind: ResourceQuota
metadata:
  name: staging-quota
  namespace: staging
spec:
  hard:
    requests.cpu: "1000m"
    requests.memory: 2Gi
    limits.cpu: "2000m"
    limits.memory: 4Gi
    pods: "20"
---
# 生产环境资源配额
apiVersion: v1
kind: ResourceQuota
metadata:
  name: prod-quota
  namespace: prod
spec:
  hard:
    requests.cpu: "1500m"
    requests.memory: 3Gi
    limits.cpu: "3000m"
    limits.memory: 6Gi
    pods: "30"
---
# 监控命名空间资源配额
apiVersion: v1
kind: ResourceQuota
metadata:
  name: monitoring-quota
  namespace: monitoring
spec:
  hard:
    requests.cpu: "300m"
    requests.memory: 512Mi
    limits.cpu: "600m"
    limits.memory: 1Gi
    pods: "5" 