# 开发环境资源配额
apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-quota
  namespace: dev
spec:
  hard:
    requests.cpu: "200m"
    requests.memory: 256Mi
    limits.cpu: "400m"
    limits.memory: 512Mi
    pods: "5"
---
# 预发布环境资源配额
apiVersion: v1
kind: ResourceQuota
metadata:
  name: staging-quota
  namespace: staging
spec:
  hard:
    requests.cpu: "200m"
    requests.memory: 256Mi
    limits.cpu: "400m"
    limits.memory: 512Mi
    pods: "5"
---
# 生产环境资源配额
apiVersion: v1
kind: ResourceQuota
metadata:
  name: prod-quota
  namespace: prod
spec:
  hard:
    requests.cpu: "300m"
    requests.memory: 512Mi
    limits.cpu: "600m"
    limits.memory: 1Gi
    pods: "8"
---
# 监控命名空间资源配额
apiVersion: v1
kind: ResourceQuota
metadata:
  name: monitoring-quota
  namespace: monitoring
spec:
  hard:
    requests.cpu: "300m"
    requests.memory: 512Mi
    limits.cpu: "600m"
    limits.memory: 1Gi
    pods: "5"
