apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure-helm
  namespace: argocd
  labels:
    app.kubernetes.io/name: infrastructure-helm
    app.kubernetes.io/part-of: infrastructure
spec:
  generators:
    - list:
        elements:
          - name: prometheus
            namespace: monitoring
            chartRepoURL: https://prometheus-community.github.io/helm-charts
            chartName: prometheus
            chartVersion: 27.28.2
            valuesRepoURL: https://github.com/lixiaojun2914/demo-infra
            valuesRevision: main
            valuesFile: gitops/infrastructure/monitoring/prometheus/values/dev.yaml
          - name: grafana
            namespace: monitoring
            chartRepoURL: https://grafana.github.io/helm-charts
            chartName: grafana
            chartVersion: 9.2.10
            valuesRepoURL: https://github.com/lixiaojun2914/demo-infra
            valuesRevision: main
            valuesFile: gitops/infrastructure/monitoring/grafana/values/dev.yaml
  template:
    metadata:
      name: "{{name}}"
      namespace: argocd
      labels:
        app.kubernetes.io/name: "{{name}}"
        app.kubernetes.io/part-of: infrastructure
    spec:
      project: infrastructure
      sources:
        - repoURL: "{{chartRepoURL}}"
          chart: "{{chartName}}"
          targetRevision: "{{chartVersion}}"
          helm:
            valueFiles:
              - "$values/{{valuesFile}}"
        - repoURL: "{{valuesRepoURL}}"
          targetRevision: "{{valuesRevision}}"
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
          - ApplyOutOfSyncOnly=true
