apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
spec:
  description: Infrastructure components (monitoring, logging, networking, etc.)

  sourceRepos:
    - "https://github.com/lixiaojun2914/demo-infra"
    - "https://istio-release.storage.googleapis.com/charts"
    - "https://prometheus-community.github.io/helm-charts"
    - "https://grafana.github.io/helm-charts"
    - "https://helm.elastic.co"
    - "https://fluent.github.io/helm-charts"
    - "https://charts.jetstack.io"
    - "https://metallb.github.io/metallb"
    - "https://charts.longhorn.io"
    - "https://bitnami-labs.github.io/sealed-secrets"

  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: istio-system
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: logging
      server: https://kubernetes.default.svc
    - namespace: cert-manager
      server: https://kubernetes.default.svc
    - namespace: metallb-system
      server: https://kubernetes.default.svc
    - namespace: longhorn-system
      server: https://kubernetes.default.svc
    - namespace: sealed-secrets
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: "rbac.authorization.k8s.io"
      kind: ClusterRole
    - group: "rbac.authorization.k8s.io"
      kind: ClusterRoleBinding
    - group: "storage.k8s.io"
      kind: StorageClass
    - group: "apiextensions.k8s.io"
      kind: CustomResourceDefinition
    - group: "admissionregistration.k8s.io"
      kind: MutatingWebhookConfiguration
    - group: "admissionregistration.k8s.io"
      kind: ValidatingWebhookConfiguration

  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret
    - group: ""
      kind: Service
    - group: ""
      kind: ServiceAccount
    - group: ""
      kind: PersistentVolumeClaim
    - group: "apps"
      kind: Deployment
    - group: "apps"
      kind: StatefulSet
    - group: "apps"
      kind: DaemonSet
    - group: "networking.k8s.io"
      kind: Ingress
    - group: "networking.k8s.io"
      kind: NetworkPolicy
    - group: "rbac.authorization.k8s.io"
      kind: Role
    - group: "rbac.authorization.k8s.io"
      kind: RoleBinding
    - group: "autoscaling"
      kind: HorizontalPodAutoscaler
    - group: "policy"
      kind: PodDisruptionBudget
    - group: "argoproj.io"
      kind: Application
    - group: "cert-manager.io"
      kind: Certificate
    - group: "cert-manager.io"
      kind: ClusterIssuer
    - group: "cert-manager.io"
      kind: Issuer
    - group: "networking.istio.io"
      kind: Gateway
    - group: "networking.istio.io"
      kind: VirtualService
    - group: "networking.istio.io"
      kind: DestinationRule
    - group: "networking.istio.io"
      kind: ServiceEntry
    - group: "networking.istio.io"
      kind: Sidecar
    - group: "networking.istio.io"
      kind: EnvoyFilter
    - group: "networking.istio.io"
      kind: WorkloadEntry
    - group: "networking.istio.io"
      kind: WorkloadGroup
    - group: "security.istio.io"
      kind: AuthorizationPolicy
    - group: "security.istio.io"
      kind: PeerAuthentication
    - group: "security.istio.io"
      kind: RequestAuthentication
    - group: "telemetry.istio.io"
      kind: Telemetry
    - group: "extensions.istio.io"
      kind: WasmPlugin
    - group: "metallb.io"
      kind: IPAddressPool
    - group: "metallb.io"
      kind: L2Advertisement
    - group: "bitnami.com"
      kind: SealedSecret
