apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: argocd

namespace: argocd

commonLabels:
  app.kubernetes.io/name: argocd
  app.kubernetes.io/part-of: gitops

resources:
  - virtualservice.yaml
