global:
  hub: docker.io/istio
  tag: 1.25.4

service:
  type: NodePort
  ports:
    - name: http2
      port: 80
      nodePort: 30080
    - name: https
      port: 443
      nodePort: 30443
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 150m
    memory: 256Mi