service:
  type: NodePort
  ports:
    # HTTP 端口
    - name: http2
      port: 80
      nodePort: 30080
      protocol: TCP
    # HTTPS 端口
    - name: https
      port: 443
      nodePort: 30443
      protocol: TCP
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 150m
    memory: 256Mi
