global:
  proxy:
    resources:
      requests:
        cpu: 25m
        memory: 32Mi
      limits:
        cpu: 200m
        memory: 128Mi
  defaultResources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 150m
      memory: 256Mi
  logging:
    level: "default:info"
  proxy:
    logLevel: "warning"
    accessLogFile: "/dev/stdout"
    accessLogFormat: ""
    accessLogEncoding: "TEXT"

pilot:
  autoscaleEnabled: false
  replicaCount: 1
  enableAnalysis: false
  enableStatus: false
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi