# 生产环境 Istio 配置
global:
  proxy:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 256Mi
  defaultResources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi
  logging:
    level: "default:info"
  proxy:
    logLevel: "info"
    accessLogFile: "/dev/stdout"
    accessLogFormat: ""
    accessLogEncoding: "TEXT"

pilot:
  autoscaleEnabled: true
  autoscaleMin: 2
  autoscaleMax: 5
  enableAnalysis: true
  enableStatus: true
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

gateways:
  istio-ingressgateway:
    autoscaleEnabled: true
    autoscaleMin: 2
    autoscaleMax: 5
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 512Mi
    service:
      ports:
        - name: http2
          port: 80
          targetPort: 8080
        - name: https
          port: 443
          targetPort: 8443

  istio-egressgateway:
    enabled: true
    autoscaleEnabled: true
    autoscaleMin: 1
    autoscaleMax: 3
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi

telemetry:
  enabled: true
  v2:
    enabled: true
    prometheus:
      enabled: true
    stackdriver:
      enabled: false
    metadata:
      enabled: true
    accessLogPolicy:
      enabled: true

tracing:
  enabled: true
  provider: jaeger
  jaeger:
    enabled: true
    template: all-in-one 