apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: grafana

namespace: monitoring

commonLabels:
  app.kubernetes.io/name: grafana
  app.kubernetes.io/part-of: monitoring

resources:
  - namespace.yaml
  - grafana-deployment.yaml
  - grafana-service.yaml
  - grafana-config.yaml
  - grafana-dashboards.yaml

configMapGenerator:
  - name: grafana-datasources
    literals:
      - datasources.yaml=|
          apiVersion: 1
          datasources:
          - name: Prometheus
            type: prometheus
            url: http://prometheus:9090
            access: proxy
            isDefault: true 