apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: grafana

namespace: monitoring

commonLabels:
  app.kubernetes.io/name: grafana
  app.kubernetes.io/part-of: monitoring

resources:
  - virtualservice.yaml
