apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBRe47A3dddYBNRdzCa0RsKBQJBErYwJgzQA8Pq4R2cZD29ZYVGlk8GZ1h8W8AmESOVxZGpjf7M+wTPqgQQtBYg/aWeWWwMfSYRll8x+8PbT38GfYkO+Mmc1VmYzSNwOL54oCeiKyJtzvo3Q/cnwpYg0K4UwcaoQeC9X7YgzJpmndxNaRLjQDMHI37sseG60Dj2weiZFCFWWGPxm//wsmoo6VL876i9VHQLdt+gHtr/Pq8puKAJZo7gCxuJbi1wV48osSb1IgAI8l+/yY4s+8l+bzogTeaaglwdb1KB+giecFj4uGGkOey2/HuAHskFNlnzTEoqXS1nG7UMxBWG+ui58NbZi9ivyW/+HPFPq6ae7zjkq3ZyEGBTxOqjddyug5NetKES0vH+CyAfaJwisYL7MF45or0eJZMUGyDL16oRUm6U4Y5ZsoAuKYhTm3bLDBcmur7V/iiN/XcA5bltBbrZqKAXJDSGDtSq/o/SMh+JKNObSkm+S+EvAb7VJRxC/woDXH+I549U0ZNUhw5jdVry2p4HDW8VKyjUEXKSyNZ0TqXc3rcYCYrmiN4n2Nkv4CY/zAXPkx3PGYfYZlDB9umONOsvuPvX0F/i6CH4TdPlwSkBUxJXsKdHY/twWk53cPjjO6BVaVs9b3BXo3OvyFFgEXWMYW3PoRVz6uwXv6oyOJP/ZYxtEjoW3JAudqXypOaXm411KJMz5ALw6KqtZpkgb1mje9aBJxOqBW/AZB/qMsVSqkJ/5JvO
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager

