apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgDJZg0eFKUkhEkaDwoRz7U/6pofKNWM9DNManwwQ4WPXY2e6+WL6pQ4jaTR5YBYN+3v1nnW6w1sE2dlhQgBikkS+EjYYZZzooTaonRH1Wv1RC17eL8w/UtF/KVJN6vrFK1rpTKlhUJYHx4ijdHZe6M9YZ91l9P/7pxRRiLAPrtqduc+taEGAsuFN8OPpcswjuA1HBMVJX9RD6jg2YKhMByGF3J+6xpi3StAK5sqLEiC2EqsuYA6RYiMSnBkgbRD5BfB5J872/BivBYyGZGMDXzxQXRMLmSFyGBLyx7W3hXRsFldbU7oqjqj/4jDSlZ7eZClNT98oyCYp/XbiPzrHfxK0J80mooMzvx6sdXADjEJYMUeH7fDGfDvFDIGZAuvuNLEPpRaiq42MteKWClghNSeHjcnBqDtlUnTbNtQe/OoK1pb5PGTE2WZd1skONW2bwaMGe+ozjL1ptSew4bUwCbXufovgCIRWmpJStx8P3T8zktPNjYwefXydnETCjDVuy9SPifGY094hWvAfilWETQ7KvIB2i/zGELB6pDp5s0vHnf2F6qxxfq/DT44ePG0HnosGJnsctf/+Tmo8LbCytBav4LhgQazemPtDtWPztRFxcGVNso+7yXWTAlFBKghBTVzMjopkWs6G0IkwQUayb6P1wIYgFoII8iJet/cP5ha3fQVzAvXIhOT7PGpuafeETAYT0CWO/bYK4UCQAPoHFYdAwdayLwbL5sPZpnLCsltOqe/YDRVVaRk
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
