apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: istio

namespace: istio-system

commonLabels:
  app.kubernetes.io/name: istio
  app.kubernetes.io/part-of: service-mesh

resources:
  - istio-gateway.yaml
