apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: istio-system
spec:
  encryptedData:
    api-token: AgBTam99YcBEZvM+EBnmAG22whUg4YBwEcp8oVj535qFCuGB6+l5ZxlRIJI0jCIUxItH4Yq23szdTmMg95iZYms/F173iPz3E3QJbSL0xt0/H4cPrXVgGqgLpz2yGV3S6C9bOwa8sCSbF1Lxy2XH8Kai0caZXpfLhz1Yho4GAn1i6CmwsxEcGLEsFyuNQVkmifzRkKos3hM8FH8Y3MTfGpDu/98YFzDOoZWi+7E39SSCvgas0mUaBfLPGqA8UyExPuRZEwHZtZfYVz8LJ+mcVR5h/VCe4OrSMqhCoIyelOnc/SgboNIZId5zDbk7QyJ3xyirQBgA3MC5iQQLsjBZYQ26Aks9t+8vIsjlkuiJ1CJQ5Xv0B4RZ0/pONBdwzIPEpdOc1+YioJI3O3Min4pWgweNuGZeA2/Vr0MAaxgUO3SaDVYYQzJ6HhG7PuUABV+Dtkb1JphG2kH5gWpYu+0xipXUBYtfd+suSMvPOBc5mNIjY3lo3UqVQ4gIxamCXWocRcDqZJWdZYvxg+6piHH3lXAVu5nP1OyYKkOgppDlPC9MCvx9N7tNAeu9EPvgkEOuDG+YLKIctx6BWfl5DLcBNP1mBDVEelyidWd3qpRE2sqKhjoCiRw9Z98Z1rnuoDPM8EAeISyaY8sqbVqOr7a3tiQlM+U1zFvaZzdVeUL12Hmk1zyuovMccY8ryQVzXs/yHas/RVmd2t951sZtjb3mlSn66Avnc/gcKBsMgbMgG7im520eYalfDRMM
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: istio-system

