apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: istio-system
spec:
  encryptedData:
    api-token: AgB/X78NqX6qOR713grPB+90O4CaV7m1SEOwKjESMce0ITJ1tNmyFDIim+qzQlk3KQQ+nhSELADwqXZDQAQGS3WnkwGvt5b4q/Z5LEW2LZdN9Nssy7PTXHfFgK1Q7Qc+W2E+9CSiyToRTromo+k+DOnhiT3SQ3HJqPuB7hAUsSzDJ9Bg8GyIXb9kMQ35Je5Apo78dSkV8X7nSfbmTfCTIBSJpeE1PQyLFGKc/HovWK0Mz0IQ/lexSdGXAeFch64cMbk29Gp54EkLfwtnVX9iQT8vQEqT3Qua5Dct4E/lWxC7rik0ADs5wL1M+SCjnqcg38tgepN9uSdL23mfnGdP6jjLKrBEWCCR9SFjdN9JeQMrZT7iI3A+JUvXAIWDJkWEqAohGf9mjWmQmHzeWq/0Mo9lZDxbkw4oOkPS8aITup/L1aKGWotPSrAyzC3aKdRylrGlPUzuzTVd1aMpkAL48/DaFOZl8+lW1xuTUrC6YxWEMgLpoKWSMP0kQij14an1vPQnrScZUzQqfJGUzv4rKefFXk+t6hwhKJAV8TH8Sz+uKF/Z+8Vo/wUtj+JUnkJmDvVqFv8wdoOG1tZN9NWeKzPULt0AMfaVkgSFvPFssLG0cTyo9lCwoph+oOTN+/fDjaMOzy6Y/LyfvDN7Ys3rxgy4f0KkENi4QJJfF3cUxEoF1RJvOEFyWi64V2vo49QOllTWQcKmJbSLT7r5CwNuVAdZMsukgXZN5nhvX1AaPd5Y9HMoYiOhezQ6
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: istio-system
