apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: sealed-secrets

namespace: sealed-secrets

commonLabels:
  app.kubernetes.io/name: sealed-secrets
  app.kubernetes.io/part-of: security

resources: []
